/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LecturesRouteRouteImport } from './routes/lectures/route'
import { Route as ToursRouteRouteImport } from './routes/tours/route'
import { Route as LecturesIndexRouteImport } from './routes/lectures/index'
import { Route as LecturesSeriesIdRouteImport } from './routes/lectures/$seriesId'
import { Route as ToursIndexRouteImport } from './routes/tours/index'
import { Route as ToursTourIdRouteImport } from './routes/tours/$tourId'
import { Route as LecturesSeriesIdEpisodeIdRouteImport } from './routes/lectures/$seriesId_.$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesRouteRoute = LecturesRouteRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRouteRoute = ToursRouteRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesIndexRoute = LecturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LecturesRouteRoute,
} as any)
const LecturesSeriesIdRoute = LecturesSeriesIdRouteImport.update({
  id: '/$seriesId',
  path: '/$seriesId',
  getParentRoute: () => LecturesRouteRoute,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRouteRoute,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/$tourId',
  path: '/$tourId',
  getParentRoute: () => ToursRouteRoute,
} as any)
const LecturesSeriesIdEpisodeIdRoute =
  LecturesSeriesIdEpisodeIdRouteImport.update({
    id: '/$seriesId_/$episodeId',
    path: '/$seriesId/$episodeId',
    getParentRoute: () => LecturesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lectures': typeof LecturesRouteRouteWithChildren
  '/tours': typeof ToursRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lectures/$seriesId': typeof LecturesSeriesIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/lectures/': typeof LecturesIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/lectures/$seriesId/$episodeId': typeof LecturesSeriesIdEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lectures/$seriesId': typeof LecturesSeriesIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/lectures': typeof LecturesIndexRoute
  '/tours': typeof ToursIndexRoute
  '/lectures/$seriesId/$episodeId': typeof LecturesSeriesIdEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lectures': typeof LecturesRouteRouteWithChildren
  '/tours': typeof ToursRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lectures/$seriesId': typeof LecturesSeriesIdRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/lectures/': typeof LecturesIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/lectures/$seriesId_/$episodeId': typeof LecturesSeriesIdEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lectures'
    | '/tours'
    | '/about'
    | '/contact'
    | '/lectures/$seriesId'
    | '/tours/$tourId'
    | '/lectures/'
    | '/tours/'
    | '/lectures/$seriesId/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/lectures/$seriesId'
    | '/tours/$tourId'
    | '/lectures'
    | '/tours'
    | '/lectures/$seriesId/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/lectures'
    | '/tours'
    | '/about'
    | '/contact'
    | '/lectures/$seriesId'
    | '/tours/$tourId'
    | '/lectures/'
    | '/tours/'
    | '/lectures/$seriesId_/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LecturesRouteRoute: typeof LecturesRouteRouteWithChildren
  ToursRouteRoute: typeof ToursRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures': {
      id: '/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof LecturesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures/': {
      id: '/lectures/'
      path: '/'
      fullPath: '/lectures/'
      preLoaderRoute: typeof LecturesIndexRouteImport
      parentRoute: typeof LecturesRouteRoute
    }
    '/lectures/$seriesId': {
      id: '/lectures/$seriesId'
      path: '/$seriesId'
      fullPath: '/lectures/$seriesId'
      preLoaderRoute: typeof LecturesSeriesIdRouteImport
      parentRoute: typeof LecturesRouteRoute
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRouteRoute
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof ToursRouteRoute
    }
    '/lectures/$seriesId_/$episodeId': {
      id: '/lectures/$seriesId_/$episodeId'
      path: '/$seriesId/$episodeId'
      fullPath: '/lectures/$seriesId/$episodeId'
      preLoaderRoute: typeof LecturesSeriesIdEpisodeIdRouteImport
      parentRoute: typeof LecturesRouteRoute
    }
  }
}

interface LecturesRouteRouteChildren {
  LecturesSeriesIdRoute: typeof LecturesSeriesIdRoute
  LecturesIndexRoute: typeof LecturesIndexRoute
  LecturesSeriesIdEpisodeIdRoute: typeof LecturesSeriesIdEpisodeIdRoute
}

const LecturesRouteRouteChildren: LecturesRouteRouteChildren = {
  LecturesSeriesIdRoute: LecturesSeriesIdRoute,
  LecturesIndexRoute: LecturesIndexRoute,
  LecturesSeriesIdEpisodeIdRoute: LecturesSeriesIdEpisodeIdRoute,
}

const LecturesRouteRouteWithChildren = LecturesRouteRoute._addFileChildren(
  LecturesRouteRouteChildren,
)

interface ToursRouteRouteChildren {
  ToursTourIdRoute: typeof ToursTourIdRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteRouteChildren: ToursRouteRouteChildren = {
  ToursTourIdRoute: ToursTourIdRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteRouteWithChildren = ToursRouteRoute._addFileChildren(
  ToursRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LecturesRouteRoute: LecturesRouteRouteWithChildren,
  ToursRouteRoute: ToursRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
